tweets_folder: ../data/tweets
user_ids_file: data/user_ids.csv
tweets_max_users: 100
tweets_per_user: 100

clustering:
  algorithm: lda
  max_iterations: 500
  max_users: 1
  alpha: default
  gamma: 0.02

twitter:
  consumer_key: 'wxwczZwiA3peVZZWq9qp3w'
  consumer_secret: 'IfD3AvPwW2DsetwTupcmQPqU0rseqtM9YNPd3e2FNgM'
  access_token: '22168865-9rIa3yIpBceZotEC4EIODh2a82fTiCqn3yow1ZoQs'
  access_token_secret: 'zogWTsVjWlkwqD0hIIf63Pu5rlX9elfAC0mOGOpbeZj4o'
